export const THRESHOLDS: Record<string, { min?: number; max?: number }> = {
  'MAIN STEAM PRESSURE': { min: 35, max: 65 },
  'MAIN STEAM TEMPERATURE': { min: 350, max: 540 },
  'TOTAL AIR FLOW ACTUAL': { min: 0, max: 100 },
  'BOILER BANK GAS OUTLET OXYGEN': { min: 2, max: 6 },
  'STACK TEMPERATOR': { min: 120, max: 200 },
  'FURNACE PRESSURE BOILER 11': { min: -10, max: 10 },
  'ECONOMIZER OUTLET TEMPERATURE': { min: 150, max: 220 },
  'ECONOMIZER INLET TEMPERATURE': { min: 120, max: 200 },
  'MAIN STEAM FLOW': { min: 100, max: 300 },
  'MAIN STEAM FLOW_1': { min: 100, max: 300 },
  'HP FEEDWATER FLOW': { min: 200, max: 300 },
  'AIR INLET APH TEMPERATURE': { min: 15, max: 35 },
  'AIR OUTLET APH TEMPERATURE': { min: 150, max: 220 },
  'AIR HEATER NB2 INLET TEMPERATURE': { min: 150, max: 200 },
  'AIR HEATER NB1 INLET TEMPERATURE': { min: 150, max: 200 },
  'BOILER BANK GAS OUTLET BOILER 11': { min: 140, max: 200 },
  'BOILER BANK GAS OUTLET TEMPERATOR': { min: 140, max: 200 },
  'WET SCRUBBER GAS INLET TEMPEATOR': { min: 130, max: 180 },
  'FLUE GAS ECONOMISER 1 INLET TEMPERATURE': { min: 150, max: 200 },
  'FLUE GAS ECONOMISER 2 INLET TEMPERATURE': { min: 140, max: 190 },
  'FLUE GAS ECONOMISER 2 OUTLET TEMPERATURE': { min: 120, max: 170 },
  'FLUE GAS AH COOL OUTLET TEMPERATURE': { min: 100, max: 150 },
  'BOILER 11 ID FAN CURRENT': { min: 30, max: 60 },
  'ID FAN NDE BEARING TEMP': { min: 50, max: 80 },
  'ID FAN DE BEARING TEMP': { min: 50, max: 80 },
  'BOILER 11 ID FAN DAMPER': { min: 50, max: 100 },
  'BOILER MASTER': { min: 70, max: 100 }
};
